site_name: dotfiles
site_author: Shant Ergenian

repo_name: tnahs/dotfiles
repo_url: https://github.com/tnahs/dotfiles/
edit_uri: ""

copyright: Copyright &copy; 2020 Shant Ergenian

theme:
  name: material

nav:
  - Python:
    - python/01-install-poetry.md
    - python/02-install-pyenv.md
    - python/03-create-a-project.md
    - python/04-setup-vscode.md
    # - python/05-testing-and-coverage.md
    - python/06-publish-to-pypi.md
  - macOS:
    # - macos/privacy.md
    - macos/restore-applebooks.md
    - macos/export-contacts.md
    - macos/sparsebundles.md
    - macos/references.md
  - NAS:
    - nas/01-router.md
    - nas/02-synology-network.md
    - nas/03-synology-data.md
    - nas/04-synology-extras.md
    - nas/05-how-to.md
    - nas/06-reference.md
  - Misc:
    - misc/npm-commands.md


markdown_extensions:
  - markdown.extensions.toc:
      permalink: true
      toc_depth: 3
  - markdown.extensions.admonition
  - markdown.extensions.smarty
  - markdown.extensions.def_list
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg