---
:default: ''
:languages:
- :key: eng
  :lang: English
- :key: ukr
  :lang: Ukrainian
- :key: tur
  :lang: Turkish
- :key: tha
  :lang: Thai
- :key: tgl
  :lang: Tagalog
- :key: swe
  :lang: Swedish
- :key: srp
  :lang: Serbian (Latin)
- :key: spa
  :lang: Spanish
- :key: slv
  :lang: Slovenian
- :key: slk
  :lang: Slovakian
- :key: ron
  :lang: Romanian
- :key: por
  :lang: Portuguese
- :key: pol
  :lang: Polish
- :key: nor
  :lang: Norwegian
- :key: nld
  :lang: Dutch
- :key: lit
  :lang: Lithuanian
- :key: lav
  :lang: Latvian
- :key: kor
  :lang: Korean
- :key: ita
  :lang: Italian
- :key: ind
  :lang: Indonesian
- :key: chr
  :lang: Cherokee
- :key: hun
  :lang: Hungarian
- :key: hin
  :lang: Hindi
- :key: heb
  :lang: Hebrew
- :key: fra
  :lang: French
- :key: fin
  :lang: Finnish
- :key: ell
  :lang: Greek
- :key: deu
  :lang: German
- :key: dan
  :lang: Danish
- :key: ces
  :lang: Czech
- :key: cat
  :lang: Catalan
- :key: bul
  :lang: Bulgarian
- :key: ara
  :lang: Arabic
- :key: jpn
  :lang: Japanese
- :key: chi_sim
  :lang: Chinese (Simplified)
- :key: chi_tra
  :lang: Chinese (Traditional)
- :key: rus
  :lang: Russian
- :key: vie
  :lang: Vietnamese
